package androidx.credentials.exceptions.domerrors;

import kotlin.jvm.internal.r;

public final class DataError extends e1.a {

    /* renamed from: b  reason: collision with root package name */
    public static final a f8782b = new a((r) null);

    public static final class a {
        public a() {
        }

        public /* synthetic */ a(r rVar) {
            this();
        }
    }

    public DataError() {
        super("androidx.credentials.TYPE_CREATE_PUBLIC_KEY_CREDENTIAL_DATA_ERROR");
    }
}
